name: Process Reminders
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  process-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Reminders
        env:
          CRON_TOKEN: ${{ secrets.CRON_SECRET_TOKEN }}
        run: |
          RESPONSE=$(curl -s -X POST \
            "https://www.huntledger.com/api/process-reminders" \
            -H "Authorization: Bearer $CRON_TOKEN" \
            -H "Content-Type: application/json" \
            -H "User-Agent: GitHub-Actions-Webhook" \
            -w "\nHTTP_STATUS: %{http_code}")

          echo "$RESPONSE"
          if ! echo "$RESPONSE" | grep -q '"success":true'; then
            echo "::error::Reminder processing failed"
            exit 1
          fi
